version: '3.8'

networks:
  unifor:
    driver: bridge

services:
  db:
    image: postgres:16
    container_name: postgres-quarkus
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: seu_banco
    ports:
      - "5432:5432"
    networks:
      - unifor
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8080"
    networks:
      - unifor

  backend:
    build:
      context: ./backend
    container_name: quarkus-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/seu_banco
      QUARKUS_DATASOURCE_USERNAME: seu_usuario
      QUARKUS_DATASOURCE_PASSWORD: sua_senha
      QUARKUS_OIDC_AUTH_SERVER_URL: http://keycloak:8080/realms/seu_realm
      QUARKUS_OIDC_CLIENT_ID: backend-client
      QUARKUS_OIDC_CREDENTIALS_SECRET: segredo
    ports:
      - "8080:8080"
    depends_on:
      - db
      - keycloak
    networks:
      - unifor

  frontend:
    build:
      context: ./frontend
    container_name: angular-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - unifor

volumes:
  postgres_data:
